@baseUrl=http://localhost:8080
@urlPath=/api/v1

###
POST {{baseUrl}}{{urlPath}}/newsale/
content-type: application/json
accept: application/json

{
"rut": "15126376",
"clientName": "Jose",
"clientLastName": "Martinez",
"clientEmail": "jgermanmm@gmail.com",
"clientPhone": "12344567",
"clientPhoneTwo": "12344567",
"clientAddress": "la casa de papito",
"clientReference": "al frente de la escuela",
"clientComuna": "MACHALI",
"clientRegion": "06 - libertador",
"plan": "PLAN ORO HD COMBO +",
"decos": 2,
"premiums": ["HBO", "TNT"],
"user": "6466d0ae226990d2b05b9ae8"
}
